language: python
python:
- '3.5'
install:
- python setup.py install
script:
- python setup.py test
deploy:
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
      tags: true
